#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
// https://www.programiz.com/online-compiler/1S57m5nf46al5

// not required for the question
#include <math.h>
#define EPSILON 0.0001f

typedef struct Particle {
    float x_position;
    float y_position;
    float x_velocity;
    float y_velocity;
} Particle;

// generated by ChatGPT (not a part of the question)
int particlesIntersect(Particle *a, Particle *b) {
    return fabs(a->x_position - b->x_position) < EPSILON &&
           fabs(a->y_position - b->y_position) < EPSILON;
}

Particle *createParticle(float x_pos, float y_pos, float x_vel, float y_vel ) {
    Particle *p = malloc(sizeof(Particle));
    assert(p);
    p->x_position = x_pos;
    p->y_position = y_pos;
    p->x_velocity = x_vel;
    p->y_velocity = y_vel;
    return p;
}

void updateParticle(Particle *particle) {
    assert(particle);
    particle->x_position += particle->x_velocity;
    particle->y_position += particle->y_velocity;
}

void displayParticle(Particle *particle) {
    assert(particle);
    printf("Particle Position :(%.2f, %.2f)\n", particle->x_position, particle->y_position);
}

void destroyParticle(Particle *particle) {
    assert(particle);
    free(particle);
}
int main(){ 
    int numParticles, steps = 10; 
    printf("Enter the number of particles: ");
    scanf("%d", &numParticles);
    Particle **particles = (Particle **)malloc(numParticles * sizeof(Particle *));

    if (particles == NULL) { 
        fprintf(stderr, "Error allocating memory\n");
        return 1; 
    } 
    for (int i = 0; i < numParticles; i++) { 
        float x_pos, y_pos, x_vel, y_vel;
        printf("Enter x_position, y_position, x_velocity, y_velocity for particle %d: ", i + 1);
        scanf("%f %f %f %f", &x_pos, &y_pos, &x_vel, &y_vel);
        particles[i] = createParticle(x_pos, y_pos, x_vel, y_vel);
    } 
    for (int t = 0; t < steps; t++) { 
        printf("Time step %d:\n", t + 1);
        for (int i = 0; i < numParticles; i++){ 
            updateParticle(particles[i]);
            displayParticle(particles[i]);
        }

        // Generated by CHATGPT - collisions
        for (int i = 0; i < numParticles; i++) {
            for (int j = i + 1; j < numParticles; j++) {
                if (particlesIntersect(particles[i], particles[j])) {
                    printf(">>> Collision detected between particle %d and %d at time %d!\n",
                        i + 1, j + 1, t + 1);
                }
            }
        }
        printf("\n");
    } 
    for (int i = 0; i < numParticles; i++){ 
        destroyParticle(particles[i]);
    } 
    free(particles);
    return 0; 
}