#include <assert.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
// https://www.programiz.com/online-compiler/9rXnvhtkQ4m9O

/***
Memory-efficient, in-place edition.
Generated by ChatGPT.

void remove_chars(char *s, const char chars[], int len) {
    int write = 0;

    for (int read = 0; s[read] != '\0'; read++) {
        char c = s[read];
        bool match = false;

        for (int j = 0; j < len; j++)
            if (c == chars[j])
                match = true;

        if (!match)
            s[write++] = c;
    }
    s[write] = '\0';
}
***/

void remove_chars(char *s, const char chars[], int len) {
    int n = strlen(s), k = 0;
    char *r = malloc((n+1) * sizeof(char));
    
    for (int i=0;i<n;i++) {
        char c = s[i];
        bool match = false;
        for (int j=0;j<len;j++) {
            if (c==chars[j]) match = true;
        }
        if (!match) r[k++] = c;
    }
    
    r[k] = '\0';
    strcpy(s, r);
    free(r);
}

int main(void) {
    char ans3[] = "aPwer fe ctx!";
    char remove[] = "!wa x";
    remove_chars(ans3, remove, 5);
    assert(strcmp(ans3,"Perfect")==0);
    return 0;
}